# Generated by Django 4.2.2 on 2023-06-11 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('post_father', models.BigIntegerField(blank=True, null=True)),
                ('archive', models.FileField(blank=True, null=True, upload_to=feed.models.post_upload_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(blank=True)),
                ('filed', models.BooleanField(blank=True)),
                ('deleted', models.BooleanField(blank=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
